name: Report

on:
  push:
    paths:
      - '.github/workflows/nightly_report.yml'
  schedule:
    - cron: '0 10 * * *'

jobs:

  nightly-report:
    name: Send Nightly Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Arrow
        shell: bash
        run: git clone https://github.com/apache/arrow
      - name: Checkout Crossbow
        shell: bash
        run: git clone https://github.com/ursacomputing/crossbow
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install Archery
        shell: bash
        run: pip install -e arrow/dev/archery[crossbow]
      - name: Send Report
        shell: bash
        env:
          CROSSBOW_GITHUB_TOKEN: ${{ secrets.CROSSBOW_GITHUB_TOKEN }}
        run: |
          job_prefix=nightly-$(date -I)
          job_id=$(archery crossbow latest-prefix ${job_prefix})
          echo "Sending report for job ${job_id}..."
          archery crossbow save_report_data \
            ${job_id}
          archery crossbow report \
            --send \
            --sender-name Crossbow \
            --sender-email 'crossbow@ursalabs.org' \
            --recipient-email 'builds@arrow.apache.org' \
            --smtp-user ${{ secrets.CROSSBOW_SMTP_USER }} \
            --smtp-password ${{ secrets.CROSSBOW_SMTP_PASSWORD }} \
            ${job_id}
